### ISSUE TITLE
Custom Properties that are nothing to do with color still get virtual text

### ISSUE THREAD

**Issue by benfrain** [brenoprata10/nvim-highlight-colors#114]
Where I have Custom Properties that are nothing to do with colours, I still see the virtual symbols:

For example:

```css
.cp-Title {
    color: var(--green-28ffbb);
    font-size: 15px;
    font-weight: 600;
    margin: var(--gutter);
}

.cp-ImageAndTitle_Title {
    font-size: 22px;
    font-family: var(--fontCondensed);
    font-variation-settings: var(--fontCondensedVariations);
    font-weight: 700;
    grid-row: 1;
    grid-column: 2;
    color: var(--grey-ffffff);
}
```

I get virtual text symbols next to font-family custom properties
