### ISSUE TITLE
See color highlight without `hsl()` function

### ISSUE THREAD

**Issue by shourov-rahman** [brenoprata10/nvim-highlight-colors#121]
Due to tailwindcss configuration and shadcn ui issue i have to keep the `globals.css` file like following. When I keep the file like that it doesn't highlight color. Is there any way I can highlight the globals.css file colors without adding `hsl()` or `rgb()` function.

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 0 0% 3.9%;
    --card: 0 0% 100%;
    --card-foreground: 0 0% 3.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 0 0% 3.9%;
    --primary: 0 72.2% 50.6%;
    --primary-foreground: 0 85.7% 97.3%; /* hsl(0 85.7% 97.3%) */
    --secondary: 0 0% 96.1%;
    --secondary-foreground: 0 0% 9%;
    --muted: 0 0% 96.1%;
    --muted-foreground: 0 0% 45.1%;
    --accent: 0 0% 96.1%;
    --accent-foreground: 0 0% 9%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 0 0% 98%;
    --border: 0 0% 89.8%;
    --input: 0 0% 89.8%;
    --ring: 0 72.2% 50.6%;
    --radius: 0.5rem;
    --chart-1: 12 76% 61%;
    --chart-2: 173 58% 39%;
    --chart-3: 197 37% 24%;
    --chart-4: 43 74% 66%;
    --chart-5: 27 87% 67%;
  }
}
```

Here is my `nvim-highlight-colors` configuration file.

```lua
return {
	"brenoprata10/nvim-highlight-colors",
	config = function()
		-- Ensure termguicolors is enabled if not already
		vim.opt.termguicolors = true

		-- Setup nvim-highlight-colors with required configurations
		require("nvim-highlight-colors").setup({
			render = "background", -- or 'foreground' or 'first_column'
			enable_hex = true, -- Highlight hex colors
			enable_short_hex = true, -- Highlight short hex colors
			enable_rgb = true, -- Highlight rgb colors
			enable_hsl = true, -- Highlight hsl colors with 'hsl' keyword
			enable_var_usage = true, -- Highlight CSS variables
			enable_named_colors = true,
			enable_tailwind = true,
		})

		-- nvim-cmp integration (if needed)
		local cmp = require("cmp")
		cmp.setup({
			-- Other configurations can be added here
			formatting = {
				format = require("nvim-highlight-colors").format,
			},
		})
	end,
	dependencies = {
		"hrsh7th/nvim-cmp",
	},
}
```
