### ISSUE TITLE
colorized areas in buffer show up at the same spot inside of the completion menu

### ISSUE THREAD

**Issue by LosFarmosCTL** [brenoprata10/nvim-highlight-colors#126]
When there are highlights inside of the main open buffer, they show up at the exact same spot (line, column) in the nvim-cmp completion menu as well. The conditions under which they show up are a bit weird though, I am not 100% sure what actually causes them to render, since for example in the screenshot below they start showing up once you have typed out `red` completely (so neither on `re` or `r` while typing the first time), stay around even if you delete one character and go back to `re`, but vanish again once you delete another one and are at only `r`. I've appended a video of that as well, along with another weird example using `white`, as well as the CSS file in which I noticed the issue, for reproduction.

This entire issue is happening even without the formatting extension for nvim-cmp, my config for this plugin is also completely empty.

<details><summary>The entire CSS file from the screenshots/video: </summary>
<p>

```css
body {
  background-color: red;
  background-image: url(background.png);
}
h1 {
  color: rgb(255, 166, 0);
  text-align: center;
  font-family: Bahnschrift;
}

.location-container {
  display: flex;
  flex-direction: column;
}

.location {
  background-color: white;
  width: 300px;
  &:hover {
    background: rgba(173, 173, 173, 0.856);
    animation: cubic-bezier(0.075, 0.82, 0.165, 1);
  }
  text-align: center;
  margin-bottom: 15px;
  font-family: Bahnschrift;
  border-radius: 6px;
  box-shadow:
    0 2px 8px 0 rgba(0, 0, 0, 0.2),
    0 2px 5px 0 rgba(0, 0, 0, 0.19);
  background: ;
}

.location-surrounding {
  display: flex;
  justify-content: center;
}
.add-container {
  display: flex;
  justify-content: center;
  margin-right: 200px;
}
.header {
  display: flex;
  justify-content: space-between;
  margin-left: 43%;
}
``` 

</p>
</details> 

<img width="576" alt="image" src="https://github.com/user-attachments/assets/ecc1bc45-ed8b-4554-a76a-fb061b242204">

https://github.com/user-attachments/assets/34733c75-11bd-4bd7-8dff-4bf7957ae575
