### ISSUE TITLE
CSS Level 4 Syntax support + disabling modern hex

### ISSUE THREAD

**Issue by rodhash** [brenoprata10/nvim-highlight-colors#147]
It seems not all HSL notation is supported.. is this planned to?

```css
body {
  background-color: var(--gray);
  color: hsl(67.29 0.8762 0.6419 / 10%);
  color: hsl(23deg, 55%, 67%)
}
```

<img width="509" alt="Image" src="https://github.com/user-attachments/assets/3ef7e9f4-968d-4a1f-91e1-ebf12e9fbda7" />

Second question:

Can I disable modern hex colors to be highlighted by this plugin? like hex w/ 8 chars? It's flickering.
```css
color: #e0f4541a
```
