### ISSUE TITLE
Support for color() function and newer color formats like lab/lch an oklab/oklch

### ISSUE THREAD

**Issue by benfrain** [brenoprata10/nvim-highlight-colors#50]
I'm sure it would be considerable work but it would be great to eventually see the newer color formats supported in this plugin.

Examples:

P3
```css
.p3 {
    --bg: color(display-p3 0 1 0);
    background-color: var(--bg);
}
```

LCH
```css
.lch-lightness {
    background: linear-gradient(
        to right,
        lch(50% 300 45) 50%,
        lch(50% 300 0) 0
    );
}
```

OKLCH

```css
.oklch {
   background-color: oklch(67.22% 0.327 329.65);
}
```
